name: PFT Issuance Tracker

on:
  schedule:
    - cron: '0 0,12 * * *'  # Runs at 00:00 and 12:00 UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  track-pft:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run PFT tracker
      run: |
        python pft_tracker.py > pft_report.txt

    - name: Update report in repository
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add pft_report.txt
        git commit -m "Update PFT issuance report" || echo "No changes to commit"
        git push 