name: PFT Tracker and Rankings

on:
  schedule:
    - cron: '0 1,13 * * *'  # Runs at 1 AM and 1 PM UTC (9 AM and 9 PM GMT+8)
  workflow_dispatch:  # Allows manual trigger

jobs:
  track-pft-and-rankings:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run PFT tracker
      run: |
        python3 pft_tracker.py > pft_report.txt
        
    - name: Update rankings
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      run: python3 update_rankings.py

    - name: Configure Git
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        
    - name: Commit and push changes
      run: |
        git add pft_report.txt address_data.json balance_history.json previous_balances.json
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update PFT tracking data and rankings" && git push) 